Repository 371bohdan/online_store, pull requests merged in 2025-02, with the labels that each got.

#11 Fix route products
  src/app.ts
  src/routes/productRoute.ts
Labels: Prev-prod, fixed

#13 Synchronisation 'prod' -> 'dev-Petsa'
  src/app.ts
  src/controllers/cartController.ts
  src/controllers/productController.ts
  src/controllers/productOptController.ts
  src/models/carts.ts
  src/models/products.ts
  src/routes/cartRoute.ts
  src/routes/orderRoute.ts
  src/routes/productOptRoute.ts
  src/routes/productRoute.ts
Labels: Sync, Prod

#21 Fixed errors that occurred when merging branches
  src/api/models/orders.ts
  src/api/services/orderService.ts
Labels: Prev-prod, fixed

#22 Fixed errors
  src/api/models/orders.ts
  src/api/services/orderService.ts
Labels: Prod, Prev-prod, fixed

#25 Added new .env variable 'FRONT_PROD_URI' to define a front prod in CORS
  src/app.ts
  src/config/dotenv/env.ts
Labels: Prod, Prev-prod, update
