Repository 371bohdan/online_store, pull requests merged in 2025-04, with the labels that each got.

#35 Lum-173,174,175,182
  src/api/controllers/productController.ts
  src/api/dto/ProductDTO.ts
  src/api/models/products.ts
  src/api/routes/productRoute.ts
  src/api/services/auxiliary/test.html
  src/api/services/auxiliary/test.ts
  src/api/services/productService.ts
  src/config/swagger/swaggerOptions.ts
Labels: Prev-prod, fixed, update, LUM Sprint 9

#38 The 'delivery' model (and any associated files or code) has been remo…
  src/api/dto/OrderDTO.ts
  src/api/middleware/errors/errorHandler.ts
  src/api/models/deliveries.ts
  src/api/models/enums/deliveryMethods.ts
  src/api/models/orders.ts
  src/api/models/users.ts
  src/api/routes/orderRoute.ts
  src/api/services/auxiliary/jwtService.ts
  src/api/services/genericCrudService.ts
  src/api/services/orderService.ts
  src/app.ts
  src/config/swagger/swaggerService.ts
Labels: enhancement, Prev-prod, LUM Sprint 10

#39 Moving the current version to 'prod'
  package-lock.json
  package.json
  src/api/controllers/productController.ts
  src/api/controllers/userSelfAccessController.ts
  src/api/dto/OrderDTO.ts
  src/api/dto/ProductDTO.ts
  src/api/dto/UserDTO.ts
  src/api/middleware/errors/errorHandler.ts
  src/api/models/deliveries.ts
  src/api/models/enums/deliveryMethods.ts
  src/api/models/orders.ts
  src/api/models/products.ts
  src/api/models/users.ts
  src/api/routes/orderRoute.ts
  src/api/routes/productRoute.ts
  src/api/routes/userSelfAccessRoute.ts
  src/api/services/authService.ts
  src/api/services/auxiliary/jwtService.ts
  src/api/services/genericCrudService.ts
  src/api/services/orderService.ts
  src/api/services/productService.ts
  src/api/services/userSelfAccessService.ts
  src/api/services/userService.ts
  src/app.ts
  src/config/mail/mailService.ts
  src/config/mail/views/order_mail.html
  src/config/swagger/swaggerOptions.ts
  src/config/swagger/swaggerService.ts
Labels: Prod, Prev-prod, update, LUM Sprint 9, LUM Sprint 10

#42 Synchronisation 'dev-Petsa' -> 'test-Petsa'
  package-lock.json
  package.json
  src/api/controllers/productController.ts
  src/api/dto/OrderDTO.ts
  src/api/dto/ProductDTO.ts
  src/api/middleware/errors/errorHandler.ts
  src/api/models/deliveries.ts
  src/api/models/enums/deliveryMethods.ts
  src/api/models/orders.ts
  src/api/models/products.ts
  src/api/models/users.ts
  src/api/routes/orderRoute.ts
  src/api/routes/productRoute.ts
  src/api/services/auxiliary/jwtService.ts
  src/api/services/auxiliary/test.html
  src/api/services/auxiliary/test.ts
  src/api/services/orderService.ts
  src/api/services/productService.ts
  src/app.ts
  src/config/swagger/swaggerOptions.ts
  src/config/swagger/swaggerService.ts
Labels: Sync

#49 Added the 'role' property
  src/api/dto/UserDTO.ts
  src/api/models/users.ts
  src/api/services/auxiliary/jwtService.ts
Labels: enhancement, Prev-prod, LUM Sprint 10
